language: cpp
script: autoreconf -i && ./configure --enable-coverage && make test
before_script:
  - ./utils/build_gtest.sh
  - gem install coveralls-lcov
after_success:
  - make coverage.info
  - coveralls-lcov coverage.info
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libboost-regex-dev
